# -*- coding: utf-8 -*-
"""01_load_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y6kD-HxgOc8Rscr-UfK6fOoln2nM-J8J
"""

import pandas as pd

data = pd.read_csv("../data/FD001.txt", sep=" ", header=None)
data.head()