# -*- coding: utf-8 -*-
"""02_train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y6kD-HxgOc8Rscr-UfK6fOoln2nM-J8J
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Load data
data = pd.read_csv("../data/FD001.txt", sep=" ", header=None)

# Take first 10 columns as features
X = data.iloc[:, :10]

# Create a dummy target (just for practice)
y = (X[0] > 100).astype(int)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Train model
model = RandomForestClassifier()
model.fit(X_train, y_train)

print("Model trained successfully!")
print("Accuracy:", model.score(X_test, y_test))